### ISSUE TITLE
Cross-platform Compatibility

### ISSUE THREAD

**Issue by AgentEpsilon** [MCOfficer/Minecraft-RPC#4]
It looks like trying to run the mod fails on macOS currently. I'm looking into it now, but I think it has to do with failing to bundle the .dylib into the jar on build.

Relevant lines of the crash report:
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Minecraft-RPC (minecraftrpc)
Caused by: java.lang.UnsatisfiedLinkError: Unable to load library 'discord-rpc': Native library (darwin/libdiscord-rpc.dylib) not found in resource path ([...resource paths...])
```

Java-DiscordRPC does include the dylib, but it must not be included correctly in Gradle.

**Comment by AgentEpsilon** [comment]
It looks like while Java-DiscordRPC does include a Darwin dylib, it's not in a release yet. This could be fixed by just depending on the master version, but I'll ask the dev to bundle a release for the latest version.

**Comment by MCOfficer** [comment]
FYI, i'll scrap this project. see the readme for more. thanks for trying to contribute!
